### ISSUE TITLE
Getting an error for the expection InvalidProperty, RuntimeFault

### ISSUE THREAD

**Issue by amoghmahesh** [vThinkBeyondVM/vThinkBVM-scripts#22]
No exception of type InvalidProperty can be thrown; an exception type must be a subclass of Throwable
No exception of type RuntimeFault can be thrown; an exception type must be a subclass of Throwable

These two are the errors which I'm getting in my eclipse IDE.
Could please tell me why? and solution to this.

Thank You

**Comment by vThinkBeyondVM** [comment]
Hi ,

Which vSphere API sample script, you are exploring? Please let me know.

**Comment by amoghmahesh** [comment]
VCESXInventoryNavigator.java

**Comment by amoghmahesh** [comment]
and in my eclipse, wherever you have used 
"ManagedEntity[] mes = new InventoryNavigator(rootFolder).searchManagedEntities("VirtualMachine")"

i am getting same error

**Comment by amoghmahesh** [comment]
in all other samples

**Comment by vThinkBeyondVM** [comment]
Can you try connecting to vCenter server using FQDN rather IP address?

**Comment by vThinkBeyondVM** [comment]
Also I would suggest you use latest YAVI Java libraries i.e. 6.0.05  and Please check here "https://github.com/yavijava/yavijava/issues/" if anybody else also faced same issue.  If there is no existing issue, it is better to raise your issue here: https://github.com/yavijava/yavijava/issues/ as more people will get visibility. I will also try to figure out.

**Comment by amoghmahesh** [comment]
Thanks for your advise...

I am using ESXi and not vCenter
